<a href="https://colab.research.google.com/github/hanamonem/flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hanamonem/flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (Ranking)
to order content or pages by their expected relevance and buisness value the model should rank the most useful results highwe than less useful ones

In [7]:
import pandas as pd

url = "https://raw.githubusercontent.com/hanamonem/flyrank-ml-internship/refs/heads/main/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(url)

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [8]:
df[['ctr', 'avg_position', 'trend_pct']].describe()

                ctr  avg_position     trend_pct
count  30000.000000   30000.00000  26612.000000
mean       0.510733      16.34238     -4.785969
std        3.279162      15.21679    473.861780
min        0.000000       0.00000   -100.000000
25%        0.000000       6.20000    -62.600000
50%        0.070000      10.80000    -33.500000
75%        0.290000      22.30000      0.000000
max      100.000000     245.00000  44900.000000

## 2. Target or proxy
the target is content ranking priority . as a proxy i would use observed user and search engine outcomes rather than a manually defined rule

In [9]:
df[['trend_pct', 'ctr', 'avg_position']].head()

   trend_pct   ctr  avg_position
0      -41.4  0.76          10.6
1      -57.7  0.05          20.3
2      -60.9  0.09          36.5
3      -13.8  0.49           6.2
4      -34.7  0.13          44.0

## 3. Success metric
NDCG is an appropriate metric because it measures how well highly relevant items appear near the top of the ranking . a higgher NDCG score indicates better ranking quality

In [10]:
df['trend_direction'].value_counts()

trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

## 4. The unit of analysis, as a real dataframe

one raw represents one content page each row contains features describing the page , such as traffic engagement metrics content characteristics and other signals used to determine ranking quality

In [11]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

Rows: 30000
Columns: 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 5. Why ML beats a fixed rule here

ranking quality dependes on many factors that interact in complex ways A fixed rule such as sorting only by traffic would ignore important signals like engagement . content freshness . machine learning can learn these patterns from data and produce better rankings than simple if-statement

In [12]:
df[['search_volume',
    'ctr',
    'avg_position',
    'engagement_rate',
    'trend_pct']].corr()

,search_volume,ctr,avg_position,engagement_rate,trend_pct
search_volume,1.000000,-0.003430,0.045354,-0.010146,0.002515
ctr,-0.003430,1.000000,-0.072590,0.096903,0.007968
avg_position,0.045354,-0.072590,1.000000,-0.017926,0.047248
engagement_rate,-0.010146,0.096903,-0.017926,1.000000,0.008412
trend_pct,0.002515,0.007968,0.047248,0.008412,1.000000

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.